<a href="https://colab.research.google.com/github/egonzalez100522276/p1-aprendizaje-automatico-100522276-100522289/blob/main/2_cargar_modelo_generar_predicciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Carga del modelo final desde GitHub y uso con los datos de competición

In [4]:
# Clonar repositorio
!git clone https://github.com/egonzalez100522276/p1-aprendizaje-automatico-100522276-100522289.git

fatal: destination path 'p1-aprendizaje-automatico-100522276-100522289' already exists and is not an empty directory.

In [5]:
# Rutas
RUTA_MODELO_FINAL = "/content/p1-aprendizaje-automatico-100522276-100522289/modelo_final.joblib"
RUTA_DATOS_COMPETICION = "/content/p1-aprendizaje-automatico-100522276-100522289/bank_ALL/bank_competition.pkl"

## Predicciones sobre el conjunto de competición
La práctica pide utilizar el modelo final para generar predicciones sobre el conjunto de competición, que no contiene la variable objetivo. Estas predicciones se guardarán en un archivo CSV llamado *predicciones.csv*.

In [6]:
import pandas as pd
import numpy as np
import joblib

# Cargar el modelo final
# Nota: En tus variables aparece como .joblib, usaremos esa ruta
pipeline_modelo_final = joblib.load(RUTA_MODELO_FINAL)

# Cargar datos de competición
df_comp = pd.read_pickle(RUTA_DATOS_COMPETICION)

print(f"Modelo cargado desde: {RUTA_MODELO_FINAL}")
print(f"Shape competición: {df_comp.shape}")
display(df_comp.head())

Modelo cargado desde: /content/p1-aprendizaje-automatico-100522276-100522289/modelo_final.joblib
Shape competición: (162, 16)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
5553,43,management,married,tertiary,no,78,yes,no,cellular,21,nov,36,1,109,1,other
915,34,housemaid,married,secondary,no,0,yes,no,unknown,30,oct,154,1,-1,0,unknown
7652,54,technician,married,secondary,no,3323,yes,yes,cellular,8,apr,59,3,-1,0,unknown
5065,43,blue-collar,single,primary,no,-399,no,yes,cellular,28,jul,662,3,-1,0,unknown
3338,35,blue-collar,married,secondary,no,262,no,no,cellular,15,mar,427,1,181,3,success

In [7]:
# Preprocesamiento de los datos de competición (siguiendo tu lógica)
df_comp_proc = df_comp.copy()

if "pdays" in df_comp_proc.columns:
    df_comp_proc["pdays_no_contacto"] = (df_comp_proc["pdays"] == -1).astype(int)
    df_comp_proc["pdays"] = df_comp_proc["pdays"].replace(-1, np.nan)

# Tratar 'unknown' como NaN en columnas categóricas
for col in ["job", "education", "contact", "poutcome"]:
    if col in df_comp_proc.columns:
        df_comp_proc[col] = df_comp_proc[col].replace("unknown", np.nan)

print("Datos preprocesados listos para predicción:")
display(df_comp_proc.head())

Datos preprocesados listos para predicción:

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,pdays_no_contacto
5553,43,management,married,tertiary,no,78,yes,no,cellular,21,nov,36,1,109.0,1,other,0
915,34,housemaid,married,secondary,no,0,yes,no,NaN,30,oct,154,1,NaN,0,NaN,1
7652,54,technician,married,secondary,no,3323,yes,yes,cellular,8,apr,59,3,NaN,0,NaN,1
5065,43,blue-collar,single,primary,no,-399,no,yes,cellular,28,jul,662,3,NaN,0,NaN,1
3338,35,blue-collar,married,secondary,no,262,no,no,cellular,15,mar,427,1,181.0,3,success,0

In [8]:
# Realizar predicciones
predicciones_comp = pipeline_modelo_final.predict(df_comp_proc)

# Crear DataFrame de resultados
predicciones_df = pd.DataFrame({
    "deposit": predicciones_comp
})

# Guardar a CSV
predicciones_df.to_csv("predicciones.csv", index=False)

print("Predicciones guardadas exitosamente en 'predicciones.csv'")
display(predicciones_df.head())

Predicciones guardadas exitosamente en 'predicciones.csv'

  deposit
0      no
1     yes
2      no
3     yes
4     yes

Con esto, queda completado el flujo principal de modelado pedido en la práctica: selección de modelo, estimación del rendimiento futuro, entrenamiento del modelo final y generación de predicciones para los datos de competición.

## Conclusión general del proceso de modelado
A lo largo de la práctica se ha seguido un proceso completo de aprendizaje automático: primero se realizó un análisis exploratorio para orientar el preprocesado, después se compararon distintas familias de modelos mediante evaluación interna, y finalmente se seleccionó la mejor alternativa para estimar su rendimiento futuro sobre test.

Tras esa evaluación, el modelo elegido se volvió a entrenar con todos los datos disponibles y se utilizó para generar predicciones sobre el conjunto de competición. De este modo, se obtiene un flujo coherente y reproducible desde el análisis inicial hasta el uso final del modelo.